import type { Notification } from './types';

const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86400_000).toISOString();

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    templateId: 'task.failed',
    category: 'task',
    severity: 'HIGH',
    title: 'Task "Daily Financial Reconciliation" execution failed',
    description: 'Process "Financial Reconciliation v3" failed on robot-fin-01: HTTP 500 Internal Server Error',
    linkUrl: '/scheduling/tasks/task-1001',
    createdAt: minutesAgo(8),
    read: false,
    variables: { taskName: '每日财务对账', processName: '财务对账', robotId: 'robot-fin-01' },
  },
  {
    id: 'notif-002',
    templateId: 'robot.offline',
    category: 'robot',
    severity: 'HIGH',
    title: 'Robot robot-fin-02 is offline',
    description: 'Heartbeat timeout 90s, may affect scheduling of related tasks',
    linkUrl: '/scheduling/robots/robot-fin-02',
    createdAt: minutesAgo(28),
    read: false,
  },
  {
    id: 'notif-003',
    templateId: 'task.timeout',
    category: 'task',
    severity: 'MEDIUM',
    title: 'Task "Customer Data Sync" execution timed out',
    description: 'Execution duration 35 minutes, exceeded preset threshold of 30 minutes',
    linkUrl: '/scheduling/tasks/task-1002',
    createdAt: minutesAgo(45),
    read: false,
  },
  {
    id: 'notif-004',
    templateId: 'license.expiring',
    category: 'license',
    severity: 'MEDIUM',
    title: 'License will expire in 15 days',
    description: 'Current license valid until 2026-05-08, please contact admin to renew',
    linkUrl: '/admin/licenses/lic-001',
    createdAt: hoursAgo(2),
    read: false,
  },
  {
    id: 'notif-005',
    templateId: 'task.permanent_failed',
    category: 'task',
    severity: 'HIGH',
    title: 'Task "Monthly Report Generation" permanently failed',
    description: 'Failed after 3 retries, manual intervention required',
    linkUrl: '/scheduling/tasks/task-1003',
    createdAt: hoursAgo(3),
    read: false,
  },
  {
    id: 'notif-006',
    templateId: 'trigger.time_failed',
    category: 'trigger',
    severity: 'MEDIUM',
    title: 'Time trigger "Daily 9AM Report" failed to fire',
    description: 'Linked process was offline at trigger time, please check trigger config',
    linkUrl: '/scheduling/triggers/trig-001',
    createdAt: hoursAgo(4),
    read: false,
  },
  {
    id: 'notif-007',
    templateId: 'task.queue_overdue',
    category: 'task',
    severity: 'MEDIUM',
    title: 'Queue task "Batch Review" queueing timed out',
    description: 'Waited 25 minutes in queue, exceeded preset threshold of 20 minutes',
    linkUrl: '/scheduling/tasks/task-1004',
    createdAt: hoursAgo(5),
    read: false,
  },
  {
    id: 'notif-008',
    templateId: 'robot.recovered',
    category: 'robot',
    severity: 'LOW',
    title: 'Robot robot-hr-01 is back online',
    description: 'Device heartbeat has recovered, ready to receive new tasks',
    linkUrl: '/scheduling/robots/robot-hr-01',
    createdAt: hoursAgo(6),
    read: true,
  },
  {
    id: 'notif-009',
    templateId: 'task.success',
    category: 'task',
    severity: 'LOW',
    title: 'Task "Monthly Data Archive" executed successfully',
    description: 'Processed 1,245 records in 8 min 32 sec',
    linkUrl: '/scheduling/tasks/task-1005',
    createdAt: hoursAgo(8),
    read: true,
  },
  {
    id: 'notif-010',
    templateId: 'task.stopped',
    category: 'task',
    severity: 'LOW',
    title: 'Task "Test Process A" was manually stopped',
    description: 'Operator: alim huang, stopped 2 hours ago',
    linkUrl: '/scheduling/tasks/task-1006',
    createdAt: hoursAgo(10),
    read: true,
  },
  {
    id: 'notif-011',
    templateId: 'robot.maintenance',
    category: 'robot',
    severity: 'LOW',
    title: '机器人 robot-it-03 进入维护模式',
    description: '由管理员手动设置维护模式，期间不接收新任务',
    linkUrl: '/scheduling/robots/robot-it-03',
    createdAt: hoursAgo(14),
    read: true,
  },
  {
    id: 'notif-012',
    templateId: 'trigger.queue_invalid',
    category: 'trigger',
    severity: 'MEDIUM',
    title: '队列触发器"工单消息队列"配置失效',
    description: '关联队列已被删除，触发器已自动暂停',
    linkUrl: '/scheduling/triggers/trig-002',
    createdAt: daysAgo(1),
    read: true,
  },
  {
    id: 'notif-013',
    templateId: 'license.expired',
    category: 'license',
    severity: 'HIGH',
    title: '附加授权"高级 OCR 模块"已过期',
    description: '相关功能已停用，请联系管理员续订',
    linkUrl: '/admin/licenses/lic-002',
    createdAt: daysAgo(1),
    read: true,
  },
  {
    id: 'notif-014',
    templateId: 'task.failed',
    category: 'task',
    severity: 'HIGH',
    title: '任务"采购单同步"执行失败',
    description: 'ERP 接口返回 401 未授权，请检查凭据有效期',
    linkUrl: '/scheduling/tasks/task-1007',
    createdAt: daysAgo(2),
    read: true,
  },
  {
    id: 'notif-015',
    templateId: 'robot.offline',
    category: 'robot',
    severity: 'HIGH',
    title: '机器人 robot-sales-01 已离线',
    description: '心跳超时 120s',
    linkUrl: '/scheduling/robots/robot-sales-01',
    createdAt: daysAgo(2),
    read: true,
  },
  {
    id: 'notif-016',
    templateId: 'task.success',
    category: 'task',
    severity: 'LOW',
    title: '任务"周报推送"执行成功',
    description: '已成功向 32 位订阅人推送本周报表',
    linkUrl: '/scheduling/tasks/task-1008',
    createdAt: daysAgo(3),
    read: true,
  },
  {
    id: 'notif-017',
    templateId: 'task.timeout',
    category: 'task',
    severity: 'MEDIUM',
    title: '任务"日志归档"执行超时',
    description: '执行时长超过 60 分钟阈值',
    linkUrl: '/scheduling/tasks/task-1009',
    createdAt: daysAgo(3),
    read: true,
  },
  {
    id: 'notif-018',
    templateId: 'license.expiring',
    category: 'license',
    severity: 'MEDIUM',
    title: '主授权将于 30 天后过期',
    description: '当前授权有效期至 2026-05-23',
    linkUrl: '/admin/licenses/lic-003',
    createdAt: daysAgo(4),
    read: true,
  },
  {
    id: 'notif-019',
    templateId: 'task.permanent_failed',
    category: 'task',
    severity: 'HIGH',
    title: '任务"客户开户审核"已永久失败',
    description: '重试 3 次后仍失败，已通知负责人',
    linkUrl: '/scheduling/tasks/task-1010',
    createdAt: daysAgo(5),
    read: true,
  },
  {
    id: 'notif-020',
    templateId: 'trigger.time_failed',
    category: 'trigger',
    severity: 'MEDIUM',
    title: '时间触发器"月末结账"触发失败',
    description: '关联机器人组下无可用机器人',
    linkUrl: '/scheduling/triggers/trig-003',
    createdAt: daysAgo(6),
    read: true,
  },
];
