import type { Notification } from './types';

const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86400_000).toISOString();

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    templateId: 'task.failed',
    category: 'task',
    severity: 'HIGH',
    title: '任务"每日财务对账"执行失败',
    description: '流程"财务对账 v3"在 robot-fin-01 上执行失败：HTTP 500 内部服务器错误',
    linkUrl: '/scheduling/tasks/task-1001',
    createdAt: minutesAgo(8),
    read: false,
    variables: { taskName: '每日财务对账', processName: '财务对账', robotId: 'robot-fin-01' },
  },
  {
    id: 'notif-002',
    templateId: 'robot.offline',
    category: 'robot',
    severity: 'HIGH',
    title: '机器人 robot-fin-02 已离线',
    description: '心跳超时 90s，可能影响关联任务的调度',
    linkUrl: '/scheduling/robots/robot-fin-02',
    createdAt: minutesAgo(28),
    read: false,
  },
  {
    id: 'notif-003',
    templateId: 'task.timeout',
    category: 'task',
    severity: 'MEDIUM',
    title: '任务"客户数据同步"执行超时',
    description: '执行时长 35 分钟，超过预设阈值 30 分钟',
    linkUrl: '/scheduling/tasks/task-1002',
    createdAt: minutesAgo(45),
    read: false,
  },
  {
    id: 'notif-004',
    templateId: 'license.expiring',
    category: 'license',
    severity: 'MEDIUM',
    title: '授权将于 15 天后过期',
    description: '当前授权有效期至 2026-05-08，请联系管理员续订',
    linkUrl: '/admin/licenses/lic-001',
    createdAt: hoursAgo(2),
    read: false,
  },
  {
    id: 'notif-005',
    templateId: 'task.permanent_failed',
    category: 'task',
    severity: 'HIGH',
    title: '任务"月度报表生成"已永久失败',
    description: '重试 3 次后仍失败，需人工介入处理',
    linkUrl: '/scheduling/tasks/task-1003',
    createdAt: hoursAgo(3),
    read: false,
  },
  {
    id: 'notif-006',
    templateId: 'trigger.time_failed',
    category: 'trigger',
    severity: 'MEDIUM',
    title: '时间触发器"每日 9 点报表"触发失败',
    description: '关联流程在触发时刻处于离线状态，请检查触发器配置',
    linkUrl: '/scheduling/triggers/trig-001',
    createdAt: hoursAgo(4),
    read: false,
  },
  {
    id: 'notif-007',
    templateId: 'task.queue_overdue',
    category: 'task',
    severity: 'MEDIUM',
    title: '队列任务"批量审核"排队超时',
    description: '在队列中等待 25 分钟，超过预设阈值 20 分钟',
    linkUrl: '/scheduling/tasks/task-1004',
    createdAt: hoursAgo(5),
    read: false,
  },
  {
    id: 'notif-008',
    templateId: 'robot.recovered',
    category: 'robot',
    severity: 'LOW',
    title: '机器人 robot-hr-01 已恢复在线',
    description: '设备心跳已恢复，可继续接收新任务',
    linkUrl: '/scheduling/robots/robot-hr-01',
    createdAt: hoursAgo(6),
    read: true,
  },
  {
    id: 'notif-009',
    templateId: 'task.success',
    category: 'task',
    severity: 'LOW',
    title: '任务"月度数据归档"执行成功',
    description: '8 分 32 秒内处理 1,245 条记录',
    linkUrl: '/scheduling/tasks/task-1005',
    createdAt: hoursAgo(8),
    read: true,
  },
  {
    id: 'notif-010',
    templateId: 'task.stopped',
    category: 'task',
    severity: 'LOW',
    title: '任务"测试流程 A"已被手动停止',
    description: '操作人：黄阿里，停止于 2 小时前',
    linkUrl: '/scheduling/tasks/task-1006',
    createdAt: hoursAgo(10),
    read: true,
  },
  {
    id: 'notif-011',
    templateId: 'robot.maintenance',
    category: 'robot',
    severity: 'LOW',
    title: '机器人 robot-it-03 进入维护模式',
    description: '由管理员手动设置维护模式，期间不接收新任务',
    linkUrl: '/scheduling/robots/robot-it-03',
    createdAt: hoursAgo(14),
    read: true,
  },
  {
    id: 'notif-012',
    templateId: 'trigger.queue_invalid',
    category: 'trigger',
    severity: 'MEDIUM',
    title: '队列触发器"工单消息队列"配置失效',
    description: '关联队列已被删除，触发器已自动暂停',
    linkUrl: '/scheduling/triggers/trig-002',
    createdAt: daysAgo(1),
    read: true,
  },
  {
    id: 'notif-013',
    templateId: 'license.expired',
    category: 'license',
    severity: 'HIGH',
    title: '附加授权"高级 OCR 模块"已过期',
    description: '相关功能已停用，请联系管理员续订',
    linkUrl: '/admin/licenses/lic-002',
    createdAt: daysAgo(1),
    read: true,
  },
  {
    id: 'notif-014',
    templateId: 'task.failed',
    category: 'task',
    severity: 'HIGH',
    title: '任务"采购单同步"执行失败',
    description: 'ERP 接口返回 401 未授权，请检查凭据有效期',
    linkUrl: '/scheduling/tasks/task-1007',
    createdAt: daysAgo(2),
    read: true,
  },
  {
    id: 'notif-015',
    templateId: 'robot.offline',
    category: 'robot',
    severity: 'HIGH',
    title: '机器人 robot-sales-01 已离线',
    description: '心跳超时 120s',
    linkUrl: '/scheduling/robots/robot-sales-01',
    createdAt: daysAgo(2),
    read: true,
  },
  {
    id: 'notif-016',
    templateId: 'task.success',
    category: 'task',
    severity: 'LOW',
    title: '任务"周报推送"执行成功',
    description: '已成功向 32 位订阅人推送本周报表',
    linkUrl: '/scheduling/tasks/task-1008',
    createdAt: daysAgo(3),
    read: true,
  },
  {
    id: 'notif-017',
    templateId: 'task.timeout',
    category: 'task',
    severity: 'MEDIUM',
    title: '任务"日志归档"执行超时',
    description: '执行时长超过 60 分钟阈值',
    linkUrl: '/scheduling/tasks/task-1009',
    createdAt: daysAgo(3),
    read: true,
  },
  {
    id: 'notif-018',
    templateId: 'license.expiring',
    category: 'license',
    severity: 'MEDIUM',
    title: '主授权将于 30 天后过期',
    description: '当前授权有效期至 2026-05-23',
    linkUrl: '/admin/licenses/lic-003',
    createdAt: daysAgo(4),
    read: true,
  },
  {
    id: 'notif-019',
    templateId: 'task.permanent_failed',
    category: 'task',
    severity: 'HIGH',
    title: '任务"客户开户审核"已永久失败',
    description: '重试 3 次后仍失败，已通知负责人',
    linkUrl: '/scheduling/tasks/task-1010',
    createdAt: daysAgo(5),
    read: true,
  },
  {
    id: 'notif-020',
    templateId: 'trigger.time_failed',
    category: 'trigger',
    severity: 'MEDIUM',
    title: '时间触发器"月末结账"触发失败',
    description: '关联机器人组下无可用机器人',
    linkUrl: '/scheduling/triggers/trig-003',
    createdAt: daysAgo(6),
    read: true,
  },
];
