import { ComponentItem } from './types';

export const commandsMockData: ComponentItem[] = [
  {
    id: 'cmd-001',
    name: 'Invoice Auto-Recognition',
    description: 'Automatically recognizes and extracts invoice data from scanned documents using OCR technology',
    type: 'command',
    tags: ['finance', 'invoice', 'OCR'],
    author: 'John Smith',
    version: '2.1.0',
    downloads: 1523,
    rating: 4.8,
    updatedAt: '2026-03-15',
    status: 'published',
    createdAt: '2025-06-10',
    dependencies: ['OCR Engine v3.2', 'PDF Parser v1.4'],
    versionHistory: [
      { version: '2.1.0', releaseDate: '2026-03-15', changelog: 'Added multi-language invoice support and improved accuracy for handwritten fields', author: 'John Smith' },
      { version: '2.0.0', releaseDate: '2026-01-20', changelog: 'Major refactor with new OCR engine integration and batch processing capability', author: 'John Smith' },
      { version: '1.5.2', releaseDate: '2025-11-05', changelog: 'Fixed date format parsing for European invoices', author: 'Sarah Chen' },
      { version: '1.0.0', releaseDate: '2025-06-10', changelog: 'Initial release with basic invoice recognition', author: 'John Smith' },
    ],
  },
  {
    id: 'cmd-002',
    name: 'Email Batch Sender',
    description: 'Sends batch emails with customizable templates and attachment support',
    type: 'command',
    tags: ['email', 'automation', 'notification'],
    author: 'Sarah Chen',
    version: '1.3.2',
    downloads: 892,
    rating: 4.5,
    updatedAt: '2026-03-10',
    status: 'published',
    createdAt: '2025-08-15',
    dependencies: ['SMTP Connector v2.0'],
    versionHistory: [
      { version: '1.3.2', releaseDate: '2026-03-10', changelog: 'Fixed attachment encoding issue for non-ASCII filenames', author: 'Sarah Chen' },
      { version: '1.3.0', releaseDate: '2026-02-01', changelog: 'Added HTML template engine and inline image support', author: 'Sarah Chen' },
      { version: '1.0.0', releaseDate: '2025-08-15', changelog: 'Initial release with basic batch sending', author: 'Sarah Chen' },
    ],
  },
  {
    id: 'cmd-003',
    name: 'File Format Converter',
    description: 'Converts documents between PDF, Word, Excel, and CSV formats with high fidelity',
    type: 'command',
    tags: ['file', 'converter', 'document'],
    author: 'Michael Lee',
    version: '3.0.1',
    downloads: 2341,
    rating: 4.9,
    updatedAt: '2026-03-20',
    status: 'published',
    createdAt: '2025-03-01',
    dependencies: ['LibreOffice Bridge v4.1', 'PDF Engine v2.3'],
    versionHistory: [
      { version: '3.0.1', releaseDate: '2026-03-20', changelog: 'Hotfix for Excel formula preservation during PDF conversion', author: 'Michael Lee' },
      { version: '3.0.0', releaseDate: '2026-03-05', changelog: 'Added CSV to Excel conversion with auto-schema detection', author: 'Michael Lee' },
      { version: '2.0.0', releaseDate: '2025-10-12', changelog: 'Introduced batch conversion mode and progress tracking', author: 'Michael Lee' },
      { version: '1.0.0', releaseDate: '2025-03-01', changelog: 'Initial release supporting PDF and Word conversions', author: 'Michael Lee' },
    ],
  },
  {
    id: 'cmd-004',
    name: 'Data Validation Engine',
    description: 'Validates structured data against configurable business rules and generates error reports',
    type: 'command',
    tags: ['validation', 'data-quality', 'rules'],
    author: 'Emily Wang',
    version: '1.0.5',
    downloads: 456,
    rating: 4.2,
    updatedAt: '2026-02-28',
    status: 'published',
    createdAt: '2025-12-01',
    dependencies: ['Rule Engine v1.2'],
    versionHistory: [
      { version: '1.0.5', releaseDate: '2026-02-28', changelog: 'Added support for cross-field validation rules', author: 'Emily Wang' },
      { version: '1.0.0', releaseDate: '2025-12-01', changelog: 'Initial release with JSON schema validation', author: 'Emily Wang' },
    ],
  },
  {
    id: 'cmd-005',
    name: 'Screenshot Capture Tool',
    description: 'Captures full-page or element-specific screenshots with configurable resolution',
    type: 'command',
    tags: ['screenshot', 'browser', 'capture'],
    author: 'David Park',
    version: '1.1.0',
    downloads: 678,
    rating: 4.3,
    updatedAt: '2026-03-05',
    status: 'published',
    createdAt: '2025-09-20',
    dependencies: ['Browser Engine v5.0'],
    versionHistory: [
      { version: '1.1.0', releaseDate: '2026-03-05', changelog: 'Added element-specific capture and viewport simulation', author: 'David Park' },
      { version: '1.0.0', releaseDate: '2025-09-20', changelog: 'Initial release with full-page screenshot', author: 'David Park' },
    ],
  },
];

export const apiConnectorsMockData: ComponentItem[] = [
  {
    id: 'api-001',
    name: 'SAP Data Connector',
    description: 'Connects to SAP ERP systems for real-time data extraction and synchronization',
    type: 'apiConnector',
    tags: ['SAP', 'ERP', 'integration'],
    author: 'Robert Zhang',
    version: '2.0.0',
    downloads: 1876,
    rating: 4.7,
    updatedAt: '2026-03-18',
    status: 'published',
    createdAt: '2025-05-15',
    dependencies: ['SAP RFC SDK v7.5'],
    versionHistory: [
      { version: '2.0.0', releaseDate: '2026-03-18', changelog: 'Full rewrite with async connection pooling and retry logic', author: 'Robert Zhang' },
      { version: '1.2.0', releaseDate: '2025-12-10', changelog: 'Added support for SAP S/4HANA Cloud APIs', author: 'Robert Zhang' },
      { version: '1.0.0', releaseDate: '2025-05-15', changelog: 'Initial release with basic BAPI/RFC calls', author: 'Robert Zhang' },
    ],
  },
  {
    id: 'api-002',
    name: 'Salesforce REST Adapter',
    description: 'Full CRUD operations on Salesforce objects via REST API with OAuth2 authentication',
    type: 'apiConnector',
    tags: ['Salesforce', 'CRM', 'REST'],
    author: 'Lisa Johnson',
    version: '1.5.3',
    downloads: 1234,
    rating: 4.6,
    updatedAt: '2026-03-12',
    status: 'published',
    createdAt: '2025-07-01',
    dependencies: ['OAuth2 Client v3.0'],
    versionHistory: [
      { version: '1.5.3', releaseDate: '2026-03-12', changelog: 'Fixed token refresh race condition in concurrent requests', author: 'Lisa Johnson' },
      { version: '1.5.0', releaseDate: '2026-01-15', changelog: 'Added bulk API support for large data operations', author: 'Lisa Johnson' },
      { version: '1.0.0', releaseDate: '2025-07-01', changelog: 'Initial release with basic CRUD operations', author: 'Lisa Johnson' },
    ],
  },
  {
    id: 'api-003',
    name: 'Slack Notification Gateway',
    description: 'Sends formatted messages and alerts to Slack channels and direct messages',
    type: 'apiConnector',
    tags: ['Slack', 'notification', 'messaging'],
    author: 'Alex Kim',
    version: '1.2.1',
    downloads: 987,
    rating: 4.4,
    updatedAt: '2026-03-08',
    status: 'published',
    createdAt: '2025-10-01',
    dependencies: ['Slack SDK v6.0'],
    versionHistory: [
      { version: '1.2.1', releaseDate: '2026-03-08', changelog: 'Added Block Kit message builder support', author: 'Alex Kim' },
      { version: '1.0.0', releaseDate: '2025-10-01', changelog: 'Initial release with channel messaging', author: 'Alex Kim' },
    ],
  },
  {
    id: 'api-004',
    name: 'Google Sheets Sync',
    description: 'Bi-directional data synchronization with Google Sheets including formula preservation',
    type: 'apiConnector',
    tags: ['Google', 'spreadsheet', 'sync'],
    author: 'Kevin Wu',
    version: '2.3.0',
    downloads: 1567,
    rating: 4.8,
    updatedAt: '2026-03-22',
    status: 'published',
    createdAt: '2025-04-20',
    dependencies: ['Google API Client v4.0'],
    versionHistory: [
      { version: '2.3.0', releaseDate: '2026-03-22', changelog: 'Added formula preservation and named range support', author: 'Kevin Wu' },
      { version: '2.0.0', releaseDate: '2025-11-30', changelog: 'Bi-directional sync with conflict resolution', author: 'Kevin Wu' },
      { version: '1.0.0', releaseDate: '2025-04-20', changelog: 'Initial release with read/write operations', author: 'Kevin Wu' },
    ],
  },
  {
    id: 'api-005',
    name: 'Workday HR Connector',
    description: 'Integrates with Workday HCM for employee data sync, payroll automation, and absence management',
    type: 'apiConnector',
    tags: ['Workday', 'HR', 'payroll', 'automation'],
    author: 'Rachel Adams',
    version: '2.1.0',
    downloads: 1432,
    rating: 4.7,
    updatedAt: '2026-03-20',
    status: 'published',
    createdAt: '2025-04-01',
    dependencies: ['Workday SOAP Client v3.0', 'OAuth2 Client v3.0'],
    versionHistory: [
      { version: '2.1.0', releaseDate: '2026-03-20', changelog: 'Added absence management and time-off request automation', author: 'Rachel Adams' },
      { version: '2.0.0', releaseDate: '2025-12-15', changelog: 'Full REST API migration with bulk employee data export', author: 'Rachel Adams' },
      { version: '1.0.0', releaseDate: '2025-04-01', changelog: 'Initial release with employee profile sync', author: 'Rachel Adams' },
    ],
  },
  {
    id: 'api-006',
    name: 'Skype Communication Bridge',
    description: 'Automates Skype messaging, meeting scheduling, and contact management via Bot Framework',
    type: 'apiConnector',
    tags: ['Skype', 'messaging', 'meeting', 'automation'],
    author: 'Daniel Park',
    version: '1.3.0',
    downloads: 756,
    rating: 4.2,
    updatedAt: '2026-03-11',
    status: 'published',
    createdAt: '2025-08-10',
    dependencies: ['Bot Framework SDK v4.21', 'Microsoft Graph Client v5.0'],
    versionHistory: [
      { version: '1.3.0', releaseDate: '2026-03-11', changelog: 'Added meeting scheduling and calendar integration', author: 'Daniel Park' },
      { version: '1.1.0', releaseDate: '2025-11-20', changelog: 'Added group chat creation and file sharing support', author: 'Daniel Park' },
      { version: '1.0.0', releaseDate: '2025-08-10', changelog: 'Initial release with direct messaging and contact sync', author: 'Daniel Park' },
    ],
  },
  {
    id: 'api-007',
    name: 'Google Cloud Platform Connector',
    description: 'Manages GCP resources including Cloud Storage, BigQuery, and Pub/Sub with service account authentication',
    type: 'apiConnector',
    tags: ['Google Cloud', 'GCP', 'BigQuery', 'cloud-storage'],
    author: 'Priya Sharma',
    version: '2.0.1',
    downloads: 1890,
    rating: 4.8,
    updatedAt: '2026-03-21',
    status: 'published',
    createdAt: '2025-03-15',
    dependencies: ['Google Cloud SDK v4.2', 'gRPC Client v1.60'],
    versionHistory: [
      { version: '2.0.1', releaseDate: '2026-03-21', changelog: 'Fixed BigQuery streaming insert timeout for large datasets', author: 'Priya Sharma' },
      { version: '2.0.0', releaseDate: '2026-01-10', changelog: 'Added Pub/Sub integration and Cloud Functions trigger support', author: 'Priya Sharma' },
      { version: '1.0.0', releaseDate: '2025-03-15', changelog: 'Initial release with Cloud Storage and BigQuery support', author: 'Priya Sharma' },
    ],
  },
  {
    id: 'api-008',
    name: 'Microsoft Teams Automation Hub',
    description: 'Automates Teams channel management, message posting, adaptive cards, and meeting lifecycle via Graph API',
    type: 'apiConnector',
    tags: ['Microsoft Teams', 'collaboration', 'messaging', 'automation'],
    author: 'Thomas Mueller',
    version: '1.4.2',
    downloads: 1678,
    rating: 4.6,
    updatedAt: '2026-03-19',
    status: 'published',
    createdAt: '2025-06-20',
    dependencies: ['Microsoft Graph SDK v5.40', 'OAuth2 Client v3.0'],
    versionHistory: [
      { version: '1.4.2', releaseDate: '2026-03-19', changelog: 'Fixed adaptive card action handling for approval workflows', author: 'Thomas Mueller' },
      { version: '1.4.0', releaseDate: '2026-02-05', changelog: 'Added meeting lifecycle automation and attendance tracking', author: 'Thomas Mueller' },
      { version: '1.2.0', releaseDate: '2025-10-15', changelog: 'Added adaptive card builder and interactive message support', author: 'Thomas Mueller' },
      { version: '1.0.0', releaseDate: '2025-06-20', changelog: 'Initial release with channel messaging and team management', author: 'Thomas Mueller' },
    ],
  },
];

export const customComponentsMockData: ComponentItem[] = [
  {
    id: 'cust-001',
    name: 'PDF Parser Widget',
    description: 'Extracts text, tables, and images from PDF documents with layout preservation',
    type: 'customComponent',
    tags: ['PDF', 'parser', 'extraction'],
    author: 'Anna Liu',
    version: '1.4.0',
    downloads: 1345,
    rating: 4.6,
    updatedAt: '2026-03-14',
    status: 'published',
    createdAt: '2025-07-20',
    dependencies: ['PDF.js v3.11', 'Canvas Renderer v2.0'],
    versionHistory: [
      { version: '1.4.0', releaseDate: '2026-03-14', changelog: 'Added table structure detection with row/column merging', author: 'Anna Liu' },
      { version: '1.2.0', releaseDate: '2025-12-05', changelog: 'Improved image extraction quality and added EXIF preservation', author: 'Anna Liu' },
      { version: '1.0.0', releaseDate: '2025-07-20', changelog: 'Initial release with text extraction', author: 'Anna Liu' },
    ],
  },
  {
    id: 'cust-002',
    name: 'Dynamic Form Builder',
    description: 'Creates data collection forms dynamically from JSON schema definitions',
    type: 'customComponent',
    tags: ['form', 'dynamic', 'schema'],
    author: 'Chris Brown',
    version: '2.1.2',
    downloads: 2100,
    rating: 4.9,
    updatedAt: '2026-03-19',
    status: 'published',
    createdAt: '2025-02-10',
    dependencies: ['JSON Schema Validator v5.0', 'Form Engine v3.1'],
    versionHistory: [
      { version: '2.1.2', releaseDate: '2026-03-19', changelog: 'Fixed conditional field visibility with nested dependencies', author: 'Chris Brown' },
      { version: '2.1.0', releaseDate: '2026-02-15', changelog: 'Added file upload fields and rich text editor integration', author: 'Chris Brown' },
      { version: '2.0.0', releaseDate: '2025-09-01', changelog: 'Complete rewrite with drag-and-drop field ordering', author: 'Chris Brown' },
      { version: '1.0.0', releaseDate: '2025-02-10', changelog: 'Initial release with basic form generation', author: 'Chris Brown' },
    ],
  },
  {
    id: 'cust-003',
    name: 'Chart Dashboard Panel',
    description: 'Configurable dashboard panel with multiple chart types and real-time data binding',
    type: 'customComponent',
    tags: ['chart', 'dashboard', 'visualization'],
    author: 'Sophie Tang',
    version: '1.0.3',
    downloads: 789,
    rating: 4.3,
    updatedAt: '2026-03-01',
    status: 'published',
    createdAt: '2025-11-15',
    dependencies: ['ECharts v5.5', 'Data Adapter v1.0'],
    versionHistory: [
      { version: '1.0.3', releaseDate: '2026-03-01', changelog: 'Fixed tooltip positioning on mobile viewports', author: 'Sophie Tang' },
      { version: '1.0.0', releaseDate: '2025-11-15', changelog: 'Initial release with bar, line, and pie chart types', author: 'Sophie Tang' },
    ],
  },
  {
    id: 'cust-004',
    name: 'Approval Workflow Designer',
    description: 'Visual designer for creating multi-level approval workflows with conditional routing',
    type: 'customComponent',
    tags: ['workflow', 'approval', 'designer'],
    author: 'James Wilson',
    version: '1.2.0',
    downloads: 654,
    rating: 4.5,
    updatedAt: '2026-03-07',
    status: 'published',
    createdAt: '2025-10-05',
    dependencies: ['Flow Engine v2.0', 'Canvas Kit v1.3'],
    versionHistory: [
      { version: '1.2.0', releaseDate: '2026-03-07', changelog: 'Added parallel approval branches and auto-escalation rules', author: 'James Wilson' },
      { version: '1.1.0', releaseDate: '2025-12-20', changelog: 'Added conditional routing based on form field values', author: 'James Wilson' },
      { version: '1.0.0', releaseDate: '2025-10-05', changelog: 'Initial release with sequential approval chains', author: 'James Wilson' },
    ],
  },
];
