import { ComponentItem } from './types';

export const commandsMockData: ComponentItem[] = [
  {
    id: 'cmd-001',
    name: 'Invoice Auto-Recognition',
    description: 'Automatically recognizes and extracts invoice data from scanned documents using OCR technology',
    type: 'command',
    tags: ['finance', 'invoice', 'OCR'],
    author: 'John Smith',
    version: '2.1.0',
    downloads: 1523,
    rating: 4.8,
    updatedAt: '2026-03-15',
    status: 'published',
  },
  {
    id: 'cmd-002',
    name: 'Email Batch Sender',
    description: 'Sends batch emails with customizable templates and attachment support',
    type: 'command',
    tags: ['email', 'automation', 'notification'],
    author: 'Sarah Chen',
    version: '1.3.2',
    downloads: 892,
    rating: 4.5,
    updatedAt: '2026-03-10',
    status: 'published',
  },
  {
    id: 'cmd-003',
    name: 'File Format Converter',
    description: 'Converts documents between PDF, Word, Excel, and CSV formats with high fidelity',
    type: 'command',
    tags: ['file', 'converter', 'document'],
    author: 'Michael Lee',
    version: '3.0.1',
    downloads: 2341,
    rating: 4.9,
    updatedAt: '2026-03-20',
    status: 'published',
  },
  {
    id: 'cmd-004',
    name: 'Data Validation Engine',
    description: 'Validates structured data against configurable business rules and generates error reports',
    type: 'command',
    tags: ['validation', 'data-quality', 'rules'],
    author: 'Emily Wang',
    version: '1.0.5',
    downloads: 456,
    rating: 4.2,
    updatedAt: '2026-02-28',
    status: 'published',
  },
  {
    id: 'cmd-005',
    name: 'Screenshot Capture Tool',
    description: 'Captures full-page or element-specific screenshots with configurable resolution',
    type: 'command',
    tags: ['screenshot', 'browser', 'capture'],
    author: 'David Park',
    version: '1.1.0',
    downloads: 678,
    rating: 4.3,
    updatedAt: '2026-03-05',
    status: 'published',
  },
];

export const apiConnectorsMockData: ComponentItem[] = [
  {
    id: 'api-001',
    name: 'SAP Data Connector',
    description: 'Connects to SAP ERP systems for real-time data extraction and synchronization',
    type: 'apiConnector',
    tags: ['SAP', 'ERP', 'integration'],
    author: 'Robert Zhang',
    version: '2.0.0',
    downloads: 1876,
    rating: 4.7,
    updatedAt: '2026-03-18',
    status: 'published',
  },
  {
    id: 'api-002',
    name: 'Salesforce REST Adapter',
    description: 'Full CRUD operations on Salesforce objects via REST API with OAuth2 authentication',
    type: 'apiConnector',
    tags: ['Salesforce', 'CRM', 'REST'],
    author: 'Lisa Johnson',
    version: '1.5.3',
    downloads: 1234,
    rating: 4.6,
    updatedAt: '2026-03-12',
    status: 'published',
  },
  {
    id: 'api-003',
    name: 'Slack Notification Gateway',
    description: 'Sends formatted messages and alerts to Slack channels and direct messages',
    type: 'apiConnector',
    tags: ['Slack', 'notification', 'messaging'],
    author: 'Alex Kim',
    version: '1.2.1',
    downloads: 987,
    rating: 4.4,
    updatedAt: '2026-03-08',
    status: 'published',
  },
  {
    id: 'api-004',
    name: 'Google Sheets Sync',
    description: 'Bi-directional data synchronization with Google Sheets including formula preservation',
    type: 'apiConnector',
    tags: ['Google', 'spreadsheet', 'sync'],
    author: 'Kevin Wu',
    version: '2.3.0',
    downloads: 1567,
    rating: 4.8,
    updatedAt: '2026-03-22',
    status: 'published',
  },
];

export const customComponentsMockData: ComponentItem[] = [
  {
    id: 'cust-001',
    name: 'PDF Parser Widget',
    description: 'Extracts text, tables, and images from PDF documents with layout preservation',
    type: 'customComponent',
    tags: ['PDF', 'parser', 'extraction'],
    author: 'Anna Liu',
    version: '1.4.0',
    downloads: 1345,
    rating: 4.6,
    updatedAt: '2026-03-14',
    status: 'published',
  },
  {
    id: 'cust-002',
    name: 'Dynamic Form Builder',
    description: 'Creates data collection forms dynamically from JSON schema definitions',
    type: 'customComponent',
    tags: ['form', 'dynamic', 'schema'],
    author: 'Chris Brown',
    version: '2.1.2',
    downloads: 2100,
    rating: 4.9,
    updatedAt: '2026-03-19',
    status: 'published',
  },
  {
    id: 'cust-003',
    name: 'Chart Dashboard Panel',
    description: 'Configurable dashboard panel with multiple chart types and real-time data binding',
    type: 'customComponent',
    tags: ['chart', 'dashboard', 'visualization'],
    author: 'Sophie Tang',
    version: '1.0.3',
    downloads: 789,
    rating: 4.3,
    updatedAt: '2026-03-01',
    status: 'published',
  },
  {
    id: 'cust-004',
    name: 'Approval Workflow Designer',
    description: 'Visual designer for creating multi-level approval workflows with conditional routing',
    type: 'customComponent',
    tags: ['workflow', 'approval', 'designer'],
    author: 'James Wilson',
    version: '1.2.0',
    downloads: 654,
    rating: 4.5,
    updatedAt: '2026-03-07',
    status: 'published',
  },
];
