// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-departments.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";
import { departmentTree } from "npm:@/mocks/departmentData";
var flatten = (nodes, path = []) => nodes.flatMap((node) => {
  const nextPath = [...path, node.name];
  return [
    { id: node.id, name: node.name, path: nextPath.join(" / ") },
    ...flatten(node.children ?? [], nextPath)
  ];
});
var list_departments_default = defineTool({
  name: "list_departments",
  title: "\u67E5\u8BE2\u90E8\u95E8\u5217\u8868",
  description: "\u5217\u51FA APA Commander \u5E73\u53F0\u7684\u7EC4\u7EC7\u90E8\u95E8\uFF08\u542B\u5C42\u7EA7\u8DEF\u5F84\uFF09\uFF0C\u53EF\u6309\u540D\u79F0\u5173\u952E\u5B57\u8FC7\u6EE4\u3002",
  inputSchema: {
    keyword: z.string().trim().optional().describe("\u6309\u90E8\u95E8\u540D\u79F0\u8FC7\u6EE4\u7684\u5173\u952E\u5B57\uFF0C\u53EF\u7701\u7565\u3002")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ keyword }) => {
    const all = flatten(departmentTree);
    const items = keyword ? all.filter((d) => d.name.includes(keyword) || d.path.includes(keyword)) : all;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { total: items.length, items }
    };
  }
});

// src/lib/mcp/tools/list-business-metrics.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { SEED_METRICS } from "npm:@/mocks/operationsMetrics/mockData";
var list_business_metrics_default = defineTool2({
  name: "list_business_metrics",
  title: "\u67E5\u8BE2\u4E1A\u52A1\u6307\u6807",
  description: "\u5217\u51FA\u8FD0\u8425\u4E2D\u5FC3\u914D\u7F6E\u7684\u4E1A\u52A1\u6307\u6807\uFF08\u7F16\u7801\u3001\u540D\u79F0\u3001\u7C7B\u578B\u3001\u5355\u4F4D\u3001\u8BF4\u660E\uFF09\uFF0C\u53EF\u6309\u5173\u952E\u5B57\u8FC7\u6EE4\u3002",
  inputSchema: {
    keyword: z2.string().trim().optional().describe("\u6309\u6307\u6807\u7F16\u7801\u6216\u540D\u79F0\u8FC7\u6EE4\u7684\u5173\u952E\u5B57\uFF0C\u53EF\u7701\u7565\u3002"),
    visible_only: z2.boolean().optional().describe("\u662F\u5426\u4EC5\u8FD4\u56DE\u53EF\u89C1\u6307\u6807\uFF0C\u9ED8\u8BA4\u8FD4\u56DE\u5168\u90E8\u3002")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ keyword, visible_only }) => {
    let items = SEED_METRICS.map((m) => ({
      id: m.id,
      code: m.code,
      displayName: m.displayName,
      metricType: m.metricType,
      unit: m.unit,
      description: m.description,
      visible: m.visible,
      updatedAt: m.updatedAt
    }));
    if (visible_only) items = items.filter((m) => m.visible);
    if (keyword) items = items.filter((m) => m.code.includes(keyword) || m.displayName.includes(keyword));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { total: items.length, items }
    };
  }
});

// src/lib/mcp/tools/get-platform-overview.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { metrics, announcements, notifications } from "npm:@/pages/Home/mockData";
var get_platform_overview_default = defineTool3({
  name: "get_platform_overview",
  title: "\u83B7\u53D6\u5E73\u53F0\u6982\u89C8",
  description: "\u83B7\u53D6 APA Commander \u9996\u9875\u6982\u89C8\uFF1A\u6838\u5FC3\u8FD0\u8425\u6307\u6807\u3001\u6700\u65B0\u5E73\u53F0\u516C\u544A\u4E0E\u5F85\u5904\u7406\u901A\u77E5\u3002",
  inputSchema: {
    include_announcements: z3.boolean().optional().describe("\u662F\u5426\u5305\u542B\u5E73\u53F0\u516C\u544A\uFF0C\u9ED8\u8BA4\u5305\u542B\u3002"),
    include_notifications: z3.boolean().optional().describe("\u662F\u5426\u5305\u542B\u901A\u77E5\uFF0C\u9ED8\u8BA4\u5305\u542B\u3002")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ include_announcements = true, include_notifications = true }) => {
    const payload = {
      metrics,
      announcements: include_announcements ? announcements : void 0,
      notifications: include_notifications ? notifications : void 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "apa-commander",
  title: "APA Commander",
  version: "0.1.0",
  instructions: "APA Commander \u81EA\u52A8\u5316\u6D41\u7A0B\u7BA1\u7406\u5E73\u53F0\u7684\u53EA\u8BFB\u5DE5\u5177\u96C6\u3002\u4F7F\u7528 get_platform_overview \u83B7\u53D6\u5E73\u53F0\u6982\u89C8\u6307\u6807\u4E0E\u516C\u544A\uFF0Clist_departments \u67E5\u8BE2\u7EC4\u7EC7\u90E8\u95E8\uFF0Clist_business_metrics \u67E5\u8BE2\u8FD0\u8425\u4E2D\u5FC3\u7684\u4E1A\u52A1\u6307\u6807\u5B9A\u4E49\u3002\u5F53\u524D\u8FD4\u56DE\u7684\u662F\u5E73\u53F0\u6F14\u793A\u6570\u636E\u3002",
  tools: [get_platform_overview_default, list_departments_default, list_business_metrics_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
