// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-departments.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/mocks/departmentData.ts
var departmentTree = [
  {
    value: "laiye",
    label: "Laiye Technology",
    children: [
      {
        value: "dept-ceo",
        label: "CEO Office"
      },
      {
        value: "dept-enterprise",
        label: "Enterprise Business Center",
        children: [
          {
            value: "dept-north",
            label: "North China Regional Business Division",
            children: [
              { value: "dept-north-solution", label: "North China Regional Solution and Delivery Team" }
            ]
          },
          { value: "dept-east", label: "East China Regional Business Division" },
          { value: "dept-south", label: "South and Southwest China Regional Business Division" },
          { value: "dept-expert", label: "Expert Enablement Group" },
          { value: "dept-prof-service", label: "Professional Services and Customer Success Management Center" }
        ]
      },
      {
        value: "dept-rd",
        label: "R&D Center",
        children: [
          {
            value: "dept-apa-product",
            label: "APA Product Division",
            children: [
              { value: "dept-fe", label: "Frontend Development Team" },
              { value: "dept-be", label: "Backend Development Team" },
              { value: "dept-ai", label: "AI Platform and Large Language Model Application R&D Team" },
              { value: "dept-qa", label: "Quality Assurance Team" },
              { value: "dept-product", label: "Product Team" }
            ]
          },
          {
            value: "dept-dw",
            label: "Digital Worker Division",
            children: [
              { value: "dept-rpa-product", label: "RPA Product Team" },
              { value: "dept-idp-product", label: "IDP Product Team" }
            ]
          },
          { value: "dept-platform", label: "Platform Engineering Division" }
        ]
      },
      { value: "dept-finance", label: "Finance Department" },
      { value: "dept-hr", label: "Human Resources Department" },
      { value: "dept-legal", label: "Legal Department" },
      { value: "dept-marketing", label: "Marketing Department" }
    ]
  }
];
var departmentPathCache = /* @__PURE__ */ new Map();
(function buildDepartmentPathCache() {
  const walk = (nodes, trail) => {
    for (const n of nodes) {
      const next = [...trail, n.label];
      departmentPathCache.set(n.value, next);
      if (n.children) walk(n.children, next);
    }
  };
  walk(departmentTree, []);
})();

// src/lib/mcp/tools/list-departments.ts
var flatten = (nodes, path = []) => nodes.flatMap((node) => {
  const nextPath = [...path, node.label];
  return [
    { id: node.value, name: node.label, path: nextPath.join(" / ") },
    ...flatten(node.children ?? [], nextPath)
  ];
});
var list_departments_default = defineTool({
  name: "list_departments",
  title: "\u67E5\u8BE2\u90E8\u95E8\u5217\u8868",
  description: "\u5217\u51FA APA Commander \u5E73\u53F0\u7684\u7EC4\u7EC7\u90E8\u95E8\uFF08\u542B\u5C42\u7EA7\u8DEF\u5F84\uFF09\uFF0C\u53EF\u6309\u540D\u79F0\u5173\u952E\u5B57\u8FC7\u6EE4\u3002",
  inputSchema: {
    keyword: z.string().trim().optional().describe("\u6309\u90E8\u95E8\u540D\u79F0\u8FC7\u6EE4\u7684\u5173\u952E\u5B57\uFF0C\u53EF\u7701\u7565\u3002")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ keyword }) => {
    const all = flatten(departmentTree);
    const items = keyword ? all.filter((d) => d.name.includes(keyword) || d.path.includes(keyword)) : all;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { total: items.length, items }
    };
  }
});

// src/lib/mcp/tools/list-business-metrics.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";

// src/mocks/operationsMetrics/mockData.ts
var SEED_METRICS = [
  {
    id: "metric-order-count",
    code: "ORDER_COUNT",
    displayName: "\u5904\u7406\u8BA2\u5355\u6570",
    metricType: "COUNTER",
    stepValue: 1,
    unit: "\u7B14",
    description: "\u7EDF\u8BA1\u5904\u7406\u5B8C\u6210\u7684\u8BA2\u5355\u6570",
    visible: true,
    createdAt: "2026-04-01T08:00:00Z",
    updatedAt: "2026-05-19T10:30:00Z",
    hasRecords: true
  },
  {
    id: "metric-invoice-amt",
    code: "INVOICE_AMT",
    displayName: "\u53D1\u7968\u91D1\u989D",
    metricType: "ACCUMULATOR",
    unit: "\u5143",
    description: "\u672C\u671F\u5F00\u5177\u53D1\u7968\u7D2F\u8BA1\u91D1\u989D",
    visible: true,
    createdAt: "2026-04-02T08:00:00Z",
    updatedAt: "2026-05-19T09:50:00Z",
    hasRecords: true
  },
  {
    id: "metric-refund-count",
    code: "REFUND_COUNT",
    displayName: "\u9000\u6B3E\u5355\u6570",
    metricType: "COUNTER",
    stepValue: 1,
    unit: "\u7B14",
    description: "\u7EDF\u8BA1\u9000\u6B3E\u5904\u7406\u5B8C\u6210\u7684\u5355\u6570",
    visible: true,
    createdAt: "2026-04-08T08:00:00Z",
    updatedAt: "2026-05-19T08:20:00Z",
    hasRecords: true
  },
  {
    id: "metric-cost-saved",
    code: "COST_SAVED",
    displayName: "\u8282\u7EA6\u6210\u672C",
    metricType: "ACCUMULATOR",
    unit: "\u5143",
    description: "\u6D41\u7A0B\u81EA\u52A8\u5316\u8282\u7EA6\u6210\u672C",
    visible: true,
    createdAt: "2026-04-10T08:00:00Z",
    updatedAt: "2026-05-19T11:10:00Z",
    hasRecords: true
  },
  {
    id: "metric-curr-status",
    code: "CURR_STATUS",
    displayName: "\u5F53\u524D\u6279\u6B21\u72B6\u6001",
    metricType: "LATEST",
    valueType: "STRING",
    unit: "",
    description: "\u6700\u65B0\u6279\u6B21\u5904\u7406\u72B6\u6001",
    visible: true,
    createdAt: "2026-04-15T08:00:00Z",
    updatedAt: "2026-05-19T11:30:00Z",
    hasRecords: true
  },
  {
    id: "metric-last-batch",
    code: "LAST_BATCH",
    displayName: "\u6700\u8FD1\u6279\u6B21\u7F16\u53F7",
    metricType: "LATEST",
    valueType: "STRING",
    unit: "",
    description: "\u6700\u8FD1\u4E00\u6B21\u53D1\u8D77\u7684\u6279\u6B21\u7F16\u53F7",
    visible: false,
    createdAt: "2026-04-20T08:00:00Z",
    updatedAt: "2026-05-19T07:00:00Z",
    hasRecords: true
  },
  {
    id: "metric-last-duration",
    code: "LAST_DURATION",
    displayName: "\u6700\u8FD1\u6279\u6B21\u8017\u65F6",
    metricType: "LATEST",
    valueType: "DECIMAL",
    unit: "\u5206\u949F",
    description: "\u6700\u8FD1\u4E00\u6B21\u6279\u6B21\u5904\u7406\u603B\u8017\u65F6",
    visible: true,
    createdAt: "2026-04-22T08:00:00Z",
    updatedAt: "2026-05-19T11:00:00Z",
    hasRecords: true
  }
];

// src/lib/mcp/tools/list-business-metrics.ts
var list_business_metrics_default = defineTool2({
  name: "list_business_metrics",
  title: "\u67E5\u8BE2\u4E1A\u52A1\u6307\u6807",
  description: "\u5217\u51FA\u8FD0\u8425\u4E2D\u5FC3\u914D\u7F6E\u7684\u4E1A\u52A1\u6307\u6807\uFF08\u7F16\u7801\u3001\u540D\u79F0\u3001\u7C7B\u578B\u3001\u5355\u4F4D\u3001\u8BF4\u660E\uFF09\uFF0C\u53EF\u6309\u5173\u952E\u5B57\u8FC7\u6EE4\u3002",
  inputSchema: {
    keyword: z2.string().trim().optional().describe("\u6309\u6307\u6807\u7F16\u7801\u6216\u540D\u79F0\u8FC7\u6EE4\u7684\u5173\u952E\u5B57\uFF0C\u53EF\u7701\u7565\u3002"),
    visible_only: z2.boolean().optional().describe("\u662F\u5426\u4EC5\u8FD4\u56DE\u53EF\u89C1\u6307\u6807\uFF0C\u9ED8\u8BA4\u8FD4\u56DE\u5168\u90E8\u3002")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ keyword, visible_only }) => {
    let items = SEED_METRICS.map((m) => ({
      id: m.id,
      code: m.code,
      displayName: m.displayName,
      metricType: m.metricType,
      unit: m.unit,
      description: m.description,
      visible: m.visible,
      updatedAt: m.updatedAt
    }));
    if (visible_only) items = items.filter((m) => m.visible);
    if (keyword) items = items.filter((m) => m.code.includes(keyword) || m.displayName.includes(keyword));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { total: items.length, items }
    };
  }
});

// src/lib/mcp/tools/get-platform-overview.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";

// src/pages/Home/mockData.ts
var metrics = [
  { key: "robots", labelKey: "homepage.metrics.robots", value: 25, trend: "up", trendValue: "+3", icon: "Bot", iconColor: "#3370FF", iconBgColor: "#F5F8FF", borderColor: "#E0EAFF" },
  { key: "processes", labelKey: "homepage.metrics.processes", value: 120, trend: "up", trendValue: "+8", icon: "Workflow", iconColor: "#7C3AED", iconBgColor: "#F8F5FF", borderColor: "#EDE5FA" },
  { key: "todayTasks", labelKey: "homepage.metrics.todayTasks", value: 345, trend: "up", trendValue: "+12%", icon: "Play", iconColor: "#FF7D00", iconBgColor: "#FFF9F5", borderColor: "#FAEADB" },
  { key: "successRate", labelKey: "homepage.metrics.successRate", value: "98.5", unit: "%", trend: "up", trendValue: "+0.3%", icon: "CheckCircle", iconColor: "#00B365", iconBgColor: "#F3FBF7", borderColor: "#D5F0E3" },
  { key: "weeklyNew", labelKey: "homepage.metrics.weeklyNew", value: 12, trend: "down", trendValue: "-3", icon: "FolderPlus", iconColor: "#3370FF", iconBgColor: "#F5F8FF", borderColor: "#E0EAFF" }
];
var notifications = [
  { id: "notif-001", titleKey: "", title: '\u4EFB\u52A1"\u6BCF\u65E5\u8D22\u52A1\u5BF9\u8D26"\u6267\u884C\u5931\u8D25', time: "8 \u5206\u949F\u524D", read: false, type: "error", priority: "URGENT", category: "task" },
  { id: "notif-002", titleKey: "", title: "\u673A\u5668\u4EBA robot-fin-02 \u5DF2\u79BB\u7EBF", time: "28 \u5206\u949F\u524D", read: false, type: "error", priority: "URGENT", category: "robot" },
  { id: "notif-003", titleKey: "", title: '\u4EFB\u52A1"\u5BA2\u6237\u6570\u636E\u540C\u6B65"\u6267\u884C\u8D85\u65F6', time: "45 \u5206\u949F\u524D", read: false, type: "warning", priority: "IMPORTANT", category: "task" },
  { id: "notif-004", titleKey: "", title: "\u6388\u6743\u5C06\u4E8E 15 \u5929\u540E\u8FC7\u671F", time: "2 \u5C0F\u65F6\u524D", read: false, type: "warning", priority: "IMPORTANT", category: "license" },
  { id: "notif-005", titleKey: "", title: '\u4EFB\u52A1"\u6708\u5EA6\u62A5\u8868\u751F\u6210"\u5DF2\u6C38\u4E45\u5931\u8D25', time: "3 \u5C0F\u65F6\u524D", read: false, type: "error", priority: "URGENT", category: "task" },
  { id: "notif-006", titleKey: "", title: '\u65F6\u95F4\u89E6\u53D1\u5668"\u6BCF\u65E5 9 \u70B9\u62A5\u8868"\u89E6\u53D1\u5931\u8D25', time: "4 \u5C0F\u65F6\u524D", read: false, type: "warning", priority: "IMPORTANT", category: "trigger" }
];
var announcements = [
  { id: "1", title: "System Maintenance: Mar 15 02:00-06:00", subtitle: "Platform will be down for maintenance, please plan ahead", time: "2026-03-12", priority: "urgent" },
  { id: "2", title: "2026 Developer Contest Registration Open", subtitle: "Win prizes and showcase your automation solutions", time: "2026-03-10", priority: "important" },
  { id: "3", title: "WEP Platform v4.5 Release Notes", subtitle: "Multiple feature improvements and bug fixes", time: "2026-03-08", priority: "normal" },
  { id: "4", title: "Security Policy Update: Password Complexity Requirements", subtitle: "Please update your password to comply with new policies", time: "2026-03-05", priority: "important" }
];

// src/lib/mcp/tools/get-platform-overview.ts
var get_platform_overview_default = defineTool3({
  name: "get_platform_overview",
  title: "\u83B7\u53D6\u5E73\u53F0\u6982\u89C8",
  description: "\u83B7\u53D6 APA Commander \u9996\u9875\u6982\u89C8\uFF1A\u6838\u5FC3\u8FD0\u8425\u6307\u6807\u3001\u6700\u65B0\u5E73\u53F0\u516C\u544A\u4E0E\u5F85\u5904\u7406\u901A\u77E5\u3002",
  inputSchema: {
    include_announcements: z3.boolean().optional().describe("\u662F\u5426\u5305\u542B\u5E73\u53F0\u516C\u544A\uFF0C\u9ED8\u8BA4\u5305\u542B\u3002"),
    include_notifications: z3.boolean().optional().describe("\u662F\u5426\u5305\u542B\u901A\u77E5\uFF0C\u9ED8\u8BA4\u5305\u542B\u3002")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ include_announcements = true, include_notifications = true }) => {
    const payload = {
      metrics,
      announcements: include_announcements ? announcements : void 0,
      notifications: include_notifications ? notifications : void 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "apa-commander",
  title: "APA Commander",
  version: "0.1.0",
  instructions: "APA Commander \u81EA\u52A8\u5316\u6D41\u7A0B\u7BA1\u7406\u5E73\u53F0\u7684\u53EA\u8BFB\u5DE5\u5177\u96C6\u3002\u4F7F\u7528 get_platform_overview \u83B7\u53D6\u5E73\u53F0\u6982\u89C8\u6307\u6807\u4E0E\u516C\u544A\uFF0Clist_departments \u67E5\u8BE2\u7EC4\u7EC7\u90E8\u95E8\uFF0Clist_business_metrics \u67E5\u8BE2\u8FD0\u8425\u4E2D\u5FC3\u7684\u4E1A\u52A1\u6307\u6807\u5B9A\u4E49\u3002\u5F53\u524D\u8FD4\u56DE\u7684\u662F\u5E73\u53F0\u6F14\u793A\u6570\u636E\u3002",
  tools: [get_platform_overview_default, list_departments_default, list_business_metrics_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
